var rule = {
    title: 'AV名湿',
    host: 'https://ftr.avms8.pics/cn/',
    url: 'https://ftr.avms8.pics/cn/home/web/index.php/vod/type/id/fyclass/page/fypage.html',
    searchUrl: 'https://ftr.avms8.pics/cn/home/web/index.php/vod/search/page/fypage/wd/**.html',
        class_parse:'.mobile_navbar_collapse&&li;a&&title;a&&href;.*/(.*?).html',
   // class_name: '主播网红&偷拍自拍&人妻熟女&强奸乱伦&制服丝袜&自慰变态&国产情色&亚洲情色&卡通&三级&欧美',
    //class_url: '20&21&22&23&24&25&26&27&28&29&30',
    searchUrl: '',
    searchable: 2,
    quickSearch: 0,
    headers: {
        'User-Agent': 'MOBILE_UA',
    },
    timeout: 5000,
    //class_parse: '#uk-nav-header li;a&&Text;a&&href;/(.*?)\.html',
    cate_exclude: '',
    play_parse: true,
    lazy: muban.mx.lazy,
    double: true,
   推荐: '.row&&.col-md-12&&.col-sm-4;.video-title&&Text;img&&src;a&&Text;a&&href',
    一级: '.row&&.col-md-9&&.col-sm-4;.video-title&&Text;img&&src;a&&Text;a&&href',
    二级: '*',
     搜索: '.s-tab-main&&li;.js-tongjic&&title;img&&src;.hint&&Text;a&&href;.pay&&Text',
}